/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebajtable;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arles Cerrato
 */
public class Main extends javax.swing.JFrame {

    // Atributos
    
    private final ArrayList<Registro> registros = new ArrayList();
    private final Registro modelo = new Registro();
    private final DefaultTableModel model_principal = new DefaultTableModel();
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NuevoCampo = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        tfNombreCampo = new javax.swing.JTextField();
        jcTipoCampo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTamanioCampo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCampos = new javax.swing.JTable();
        jButtonAgregarCampo = new javax.swing.JButton();
        jButtonEliminarCampo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_principal = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonAgregarRegistro = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jcTipoCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "String", "Int", "Double", "Boolean" }));

        jLabel2.setText("Tipo");

        jLabel3.setText("Size");

        tablaCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Tamaño"
            }
        ));
        jScrollPane2.setViewportView(tablaCampos);

        jButtonAgregarCampo.setText("Agregar");
        jButtonAgregarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCampoActionPerformed(evt);
            }
        });

        jButtonEliminarCampo.setText("Eliminar");
        jButtonEliminarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCampoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NuevoCampoLayout = new javax.swing.GroupLayout(NuevoCampo.getContentPane());
        NuevoCampo.getContentPane().setLayout(NuevoCampoLayout);
        NuevoCampoLayout.setHorizontalGroup(
            NuevoCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevoCampoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(NuevoCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEliminarCampo)
                    .addComponent(jButtonAgregarCampo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(NuevoCampoLayout.createSequentialGroup()
                .addGroup(NuevoCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevoCampoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(NuevoCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(NuevoCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcTipoCampo, 0, 156, Short.MAX_VALUE)
                            .addComponent(tfNombreCampo))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfTamanioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NuevoCampoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButtonCancelar)
                        .addGap(127, 127, 127)
                        .addComponent(jButtonAceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NuevoCampoLayout.setVerticalGroup(
            NuevoCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevoCampoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(NuevoCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfTamanioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NuevoCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcTipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(NuevoCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevoCampoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NuevoCampoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButtonAgregarCampo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarCampo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(NuevoCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAceptar))
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_principal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_principal);

        jButton1.setText("Agregar Model");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAgregarRegistro.setText("Agregar Registro");
        jButtonAgregarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarRegistroActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar Registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgregarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAgregarRegistro)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCampoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaCampos.getModel();
        String nombre, tipo;
        int size;
        nombre = tfNombreCampo.getText();
        if (nombre.equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre esta vacio");
            return;
        }
        tipo = jcTipoCampo.getSelectedItem().toString();
        try {
            size = Integer.parseInt(tfTamanioCampo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en la casilla tamaño.");
            return;
        }
        Campos campos = new Campos(nombre, size, tipo);
        Object rowData [] = {nombre, tipo, size};
        model.addRow(rowData);
        modelo.agregarCampo(campos);
    }//GEN-LAST:event_jButtonAgregarCampoActionPerformed

    private void jButtonEliminarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCampoActionPerformed
        if (tablaCampos.getSelectedRow()>-1) {
            modelo.eliminarCampo(tablaCampos.getSelectedRow());
            DefaultTableModel model = (DefaultTableModel) tablaCampos.getModel();
            model.removeRow(tablaCampos.getSelectedRow());
            JOptionPane.showMessageDialog(this, "Se ha eliminado el campo");
        }
    }//GEN-LAST:event_jButtonEliminarCampoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        NuevoCampo.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        int seleccion = JOptionPane.showConfirmDialog(this, "Desea guardar los cambios.");
        if (JOptionPane.OK_OPTION==seleccion) {
            JOptionPane.showMessageDialog(this, "Se ha guardado los cambios.");
            NuevoCampo.setVisible(false);
            tabla_principal.setModel(model_principal);
            modelo.getCampos().forEach((campo)->{
                model_principal.addColumn(campo.getNombre());
            });
            Object rowData[] = {};
            model_principal.addRow(rowData);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NuevoCampo.setModal(true);
        NuevoCampo.pack();
        NuevoCampo.setLocationRelativeTo(null);
        NuevoCampo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAgregarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarRegistroActionPerformed
        try {
            Registro registro = new Registro();
            ArrayList<Campos> campos = (ArrayList<Campos>)modelo.getCampos().clone();
            registro.setCampos(campos);
            for (int i = 0; i < model_principal.getColumnCount(); i++) {
                System.out.println(model_principal.getValueAt(model_principal.getRowCount()-1, i).toString());
                registro.getCampo(i).setContent(model_principal.getValueAt(model_principal.getRowCount()-1, i).toString());
            }
            Object rowData [] = {};
            model_principal.addRow(rowData);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar el registro");
            for (int i = 0; i < model_principal.getColumnCount(); i++) {
                model_principal.setValueAt("", model_principal.getRowCount()-1, i);
            }
        }
    }//GEN-LAST:event_jButtonAgregarRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog NuevoCampo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAgregarCampo;
    private javax.swing.JButton jButtonAgregarRegistro;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminarCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcTipoCampo;
    private javax.swing.JTable tablaCampos;
    private javax.swing.JTable tabla_principal;
    private javax.swing.JTextField tfNombreCampo;
    private javax.swing.JTextField tfTamanioCampo;
    // End of variables declaration//GEN-END:variables
}
